name: Deploy

on:
  workflow_dispatch:
  push:
    paths:
    - "Dockerfile"
    - "configs/production/*.conf"
    - "scripts/*.sh"
    branches:
    - "main"

jobs:

    us-east-1:
      uses: ./.github/workflows/deploy-us-east-1-prd.yml
      with:
          region: us-east-1
    
    us-east-2:
        needs: [us-east-1]
        uses: ./.github/workflows/deploy-us-east-2-prd.yml
        with:
          region: us-east-2
