name: Regiao

on:
  workflow_call:
    inputs:
      region:
        type: string
        description: 'Região'
        required: true

jobs:
  
  show_region:
    runs-on: ubuntu-latest
    steps:
      - name: Write somthing to log
        run: |
            echo "Iniciando a action de deploy na região de ${{inputs.region}}"

  build: 
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.push.outputs.image }}
      tag: ${{ steps.push.outputs.tag }}
    steps:
      - name: Check for existing image and tag
        id: check
        run: |
          if [ -f image_info.txt ]; then
            echo "Image and tag already exist. Reading values..."
            source image_info.txt
            echo "::set-output name=image::$image"
            echo "::set-output name=tag::$tag"
            exit 0
          fi
          echo "No existing image and tag. Proceeding with build..."
      - uses: actions/checkout@v3
      - name: Write somthing to log
        run: |
          echo "Deploy regiao 1"

      - name: Push image to ECR
        if: steps.check.conclusion != 'success'
        id: push
        run: |
          echo "image=hello" >> "$GITHUB_OUTPUT"
          echo "tag=world" >> "$GITHUB_OUTPUT"
      

      - name: Save image and tag to artifact
        if: steps.check.conclusion != 'success'
        run: |
          echo "image=${{ steps.push.outputs.image }}" > image_info.txt
          echo "tag=${{ steps.push.outputs.tag }}" >> image_info.txt
    
      - name: Upload artifact
        if: steps.check.conclusion != 'success'
        uses: actions/upload-artifact@v3
        with:
          name: image-info
          path: image_info.txt
          

  use-variables:
    runs-on: medium-runner
    needs: [build]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: image-info
        path: .

    - name: Read variables from file
      id: read-vars
      run: |
        source image_info.txt
        echo "IMAGE=$image"
        echo "TAG=$tag"
        echo "::set-output name=image::$image"
        echo "::set-output name=tag::$tag"
      shell: bash

    - name: Use variables
      run: echo "Using IMAGE=$image and TAG=$tag"
      env:
        IMAGE: ${{ steps.read-vars.outputs.image }}
        TAG: ${{ steps.read-vars.outputs.tag }}

  product_approve:
    needs: [build]
    runs-on: ubuntu-latest
    environment: product_approve
    steps:
      - name: Write somthing to log
        run: |
              echo "Deploy regiao 2"

  tech_approve:
    needs: [build]
    runs-on: ubuntu-latest
    environment: tech_approve
    steps:
      - name: Write somthing to log
        run: |
              echo "Deploy regiao 2"

  start_job:
    needs: [product_approve, tech_approve]
    runs-on: small-runner
    environment: start_job
    steps:      
      - name: Show who started the job
        run: |
          echo "Iniciando o deploy na região de ${{inputs.region}}.
          Este job foi iniciado por: $GITHUB_ACTOR"
  
  done:
    needs: [start_job]
    runs-on: ubuntu-latest
    steps:
      - name: finalização
        run: |
          echo "finalizado"