name: Deploy

on:
  workflow_dispatch:

jobs:

    us-east-1:
      uses: ./.github/workflows/deploy-us-east-1-prd.yml
      with:
          region: us-east-1
    
    us-east-2:
        uses: ./.github/workflows/deploy-us-east-2-prd.yml
        with:
          region: us-east-2
